### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cromidia** [aztecrabbit/libinject#1]
# github.com/aztecrabbit/libinject
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:211:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:212:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:213:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:214:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:215:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:216:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:217:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:218:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:219:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:220:21: undefined: strings.ReplaceAll
/root/go/src/github.com/aztecrabbit/libinject/libinject.go:220:21: too many errors

**Comment by aztecrabbit** [comment]
Use golang version 1.13 and above

**Comment by cromidia** [comment]
I am use version 2:1.10
