### ISSUE TITLE
SSL + Payload Tunnel Type

### ISSUE THREAD

**Issue by mukswilly** [aztecrabbit/libinject#2]
Hello, thanks for the great work. Is it possible for you to add the SSL + Payload Tunnel type?

**Comment by aztecrabbit** [comment]
Hi, i'm not maintaining this project anymore, i'm sorry.

**Comment by mukswilly** [comment]
> Hi, i'm not maintaining this project anymore, i'm sorry.

Alright. Thanks for the reply. However, I would like to inquire. Is their a way I can personally get in contact with you?

**Comment by aztecrabbit** [comment]
Yes. This is my telegram account @aztecrabbit

**Comment by mukswilly** [comment]
> Yes. This is my telegram account @aztecrabbit

Thanks. I will be in touch with you shortly. Nice time
